-- Retail-Sales-Analysis Project
-- Author: Jayshree Patidar
-- Description: SQL analysis on retail sales dataset


-- 1. DATABASE SETUP

-- Creating Database
CREATE DATABASE retail_sales_project;


-- 2. TABLE CREATION

-- Creating The Ratail Sales Table
CREATE TABLE retail_sales(
	transactions_id INT PRIMARY KEY,
	sale_date DATE,
	sale_time TIME,
	customer_id INT,  
	gender VARCHAR(15),
	age INT,
	category VARCHAR(20),
	quantiy INT,     
	price_per_unit NUMERIC(10,2),
	cogs NUMERIC(10,2),
	total_sale NUMERIC(10,2)
);


-- 3. DATA PREVIEW AND EXPLORATION QUERIES 

-- Count total records in dataset
SELECT COUNT(*) FROM retail_sales;

-- Total number of sales
SELECT COUNT(*) AS total_sales
FROM retail_sales;

-- Total number of customers
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM retail_sales;

-- Number of product categories
SELECT DISTINCT category
FROM retail_sales;

-- Date range of dataset
SELECT 
    MIN(sale_date) AS start_date,
    MAX(sale_date) AS end_date
FROM retail_sales;


-- 4. DATA CLEANING

-- Check for NULL values
SELECT *
FROM retail_sales
WHERE
    transactions_id IS NULL
    OR sale_date IS NULL
    OR sale_time IS NULL
    OR gender IS NULL
    OR category IS NULL
    OR quantity IS NULL
	OR price_per_unit IS NULL
    OR cogs IS NULL
    OR total_sale IS NULL;



-- Count rows with NULL values
SELECT COUNT(*) AS null_count
FROM retail_sales
WHERE
    transactions_id IS NULL
    OR sale_date IS NULL
    OR sale_time IS NULL
    OR gender IS NULL
    OR category IS NULL
    OR quantity IS NULL
	OR price_per_unit IS NULL
    OR cogs IS NULL
    OR total_sale IS NULL;

 -- Delete NULL records
DELETE FROM retail_sales
WHERE 
    transactions_id IS NULL
    OR sale_date IS NULL
    OR sale_time IS NULL
    OR gender IS NULL
    OR category IS NULL
    OR quantity IS NULL
	OR price_per_unit IS NULL
    OR cogs IS NULL
    OR total_sale IS NULL;



-- Check duplicate transactions
SELECT transactions_id, COUNT(*)
FROM retail_sales
GROUP BY transactions_id
HAVING COUNT(*) > 1;


-- 5. BUSINESS ANALYSIS
-- Basic Queries
-- 1.	Retrieve all sales records from the dataset.
SELECT * FROM retail_sales;


-- 2.	Show all transactions where the category is Clothing.
SELECT * FROM retail_sales
WHERE category = 'Clothing';


-- 3.	Find all sales made on 2022-11-05.
SELECT * FROM retail_sales
WHERE sale_date = '2022-11-05';


-- 4.	Retrieve transactions where total_sale > 1000.
SELECT * FROM retail_sales
WHERE total_sale > 1000;


-- Aggregation & Summary Analysis
-- 6.	Find the total number of transactions in the dataset.
SELECT 
	COUNT(transactions_id) AS total_transaction_no 
FROM retail_sales;


-- 7.	Calculate the total revenue generated from all sales.
SELECT 
	SUM(total_sale) AS total_revenue
FROM retail_sales;


-- 8.	Find the average sale value per category.
SELECT
	category,
	ROUND(AVG(total_sale),2) AS average_sale
FROM retail_sales
GROUP BY category;

-- 9.	Calculate the total quantity sold for each category.
SELECT 
	category,
	SUM(quantity) AS total_quantity
FROM retail_sales
GROUP BY category;


-- 10.Calculate the total revenue generated by each gender.
SELECT 
	gender,
	SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY gender;


-- Time-Based Sales Analysis
-- 11.	Identify the month with the highest sales.

SELECT 
    DATE_TRUNC('month', sale_date) AS sales_month,
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY sales_month
ORDER BY total_sales DESC
LIMIT 1;


--  12. Determine which time of day has the most sales (morning / afternoon / evening).
SELECT 
    CASE 
        WHEN sale_time < '12:00:00' THEN 'Morning'
        WHEN sale_time BETWEEN '12:00:00' AND '17:00:00' THEN 'Afternoon'
        ELSE 'Evening'
    END AS time_of_day,
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY time_of_day
ORDER BY total_sales DESC;


-- 13. Find the transactions where total_sale is greater than the average sale. 
SELECT *
FROM retail_sales
WHERE total_sale > (
    SELECT AVG(total_sale)
    FROM retail_sales
);


-- 14. Identify customers whose total purchases are above the overall average purchase amount. 
SELECT customer_id,
       SUM(total_sale) AS total_purchase
FROM retail_sales
GROUP BY customer_id
HAVING SUM(total_sale) >
       (SELECT AVG(total_sale) FROM retail_sales)
ORDER BY customer_id;


-- Customer Behavior Analysi
-- 15. Find customers who made multiple transactions on the same day.
SELECT a.customer_id, a.sale_date, COUNT(*) AS transactions
FROM retail_sales a
GROUP BY a.customer_id, a.sale_date
HAVING COUNT(*) > 1
ORDER BY transactions DESC;

-- 16. Which gender spends more on average? 
SELECT gender,
       ROUND(AVG(total_sale),2) AS avg_spending
FROM retail_sales
GROUP BY gender
ORDER BY avg_spending DESC;


-- 17. Identify the top 5 highest spending customers. 
SELECT customer_id,
       SUM(total_sale) AS total_spent
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 5;


-- 18. Find the top 10 highest value transactions.
SELECT *
FROM retail_sales
ORDER BY total_sale DESC
LIMIT 10;


-- 19. Which age group contributes the most revenue? 
SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 60 THEN '46-60'
        ELSE '60+'
    END AS age_group,
    SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Advanced SQL Analysis
-- 20. Find the Top 3 Transactions in Each Category
SELECT *
FROM (
    SELECT 
        transactions_id,
        category,
        total_sale,
        RANK() OVER (PARTITION BY category ORDER BY total_sale DESC) AS rank
    FROM retail_sales
) t
WHERE rank <= 3;


-- 21. Find Customers Who Spend More Than Their Category Average
SELECT r.customer_id,
       r.category,
       r.total_sale
FROM retail_sales r
JOIN (
    SELECT category,
           AVG(total_sale) AS avg_category_sale
    FROM retail_sales
    GROUP BY category
) c
ON r.category = c.category
WHERE r.total_sale > c.avg_category_sale
ORDER BY category;


-- Q.22 Find customers who purchased in more than one category
SELECT 
    customer_id,
    COUNT(DISTINCT category) AS categories_purchased
FROM retail_sales
GROUP BY customer_id
HAVING COUNT(DISTINCT category) > 1
ORDER BY categories_purchased DESC;


-- Q.23 Find the busiest sales hour
SELECT 
    EXTRACT(HOUR FROM sale_time) AS hour,
    COUNT(*) AS total_transactions
FROM retail_sales
GROUP BY hour
ORDER BY total_transactions DESC
LIMIT 1;

-- Q.24 What are the total sales by weekday?
SELECT 
    TO_CHAR(sale_date,'Day') AS weekday,
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY weekday
ORDER BY total_sales DESC;


-- Q.25 Which category sells the most per customer on average?
SELECT 
    category,
    ROUND(SUM(total_sale) / COUNT(DISTINCT customer_id),2) AS avg_sales_per_customer
FROM retail_sales
GROUP BY category
ORDER BY avg_sales_per_customer DESC;






